name: CI Opentest
on: 
  push:
    branches:
      - 'master'
jobs:

  copy:
    name: Copy-SSH
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- name: Listar directorio
    # run: ls -R .
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "tests, macros"
        target: /docker/opentest/test-repo
        rm: true
  reload:
    name: Reload Container
    needs: copy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /docker/opentest && docker compose build opentest && docker compose -f /docker/opentest/docker-compose.yml up -d
